#!/bin/bash
DIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $DIR;

node r.js -convert ../bean/ ../src/vendors/
node r.js -convert ../qwery/ ../src/vendors/
node r.js -convert ../bonzo/ ../src/vendors/
node r.js -convert ../morpheus/ ../src/vendors/
cp ../reqwest/reqwest.js ../src/vendors/reqwest.js
